# Generated by Django 3.2.20 on 2023-08-24 02:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
