# Generated by Django 3.2.20 on 2023-08-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bima', '0002_alter_policy_policy_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
